### ISSUE TITLE
Feature request: Get\Set Eq setting

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#108]
I would like to be able to get and set Eq setting via this.
The main reason is with the Playbar it has features like night mode and voice enhancement(DialogLevel) and I want an easy on off toggle.

Let me know if this doesn't make sense.

Bellow is some SOAP commands

The SOAP action takes three variables: 
InstanceID which is 0
EQType: which is the action (eg NightMode or DialogLevel)
DesiredValue: in the case of this example it's 0 or 1

``` xml
POST /MediaRenderer/RenderingControl/Control HTTP/1.1
HOST: 192.168.1.X:1400
SOAPACTION: "urn:schemas-upnp-org:service:RenderingControl:1#SetEQ"
CONTENT-TYPE: text/xml; charset="utf-8"
Content-Length: 414

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <u:SetEQ xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
         <InstanceID>0</InstanceID>
         <EQType>NightMode</EQType>
         <DesiredValue>0</DesiredValue>
      </u:SetEQ>
   </s:Body>
```

**Comment by jishi** [comment]
DialogLevel sounds like something that takes a range, do you know which it is? I don't own a playbar myself, so I would require someones assistance in testing and evaluating this.

**Comment by NovaGL** [comment]
Happy to test out, that was the output from DeviceSpy. I think its just a poor choice of words. Meaning regular dialog or enhanced "The Speech Enhancement setting makes the TV dialog easier to hear"

**Comment by jishi** [comment]
Okay, and those two settings aren't mutually exclusive? You can have NightMode and DialogLevel activated at the same time?

**Comment by NovaGL** [comment]
That is correct.

These are the EqTypes you can have, I don't have a Sub or surround sound so can't test the others

NightMode, DialogLevel, AudioDelay, SurroundEnable, SurroundMode, SurroundLevel, SubCrossover, SubPolarity, SubGain, SubEnable

To get the current status is much the same as setting it.

```xml
 <s:Envelope
        xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
        s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:GetEQ
                xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
                <InstanceID>
                    0
                    </InstanceID>
                <EQType>
                    DialogLevel
                    </EQType>
                </u:GetEQ>
            </s:Body>
        </s:Envelope>
```
See attached.

![capture](https://cloud.githubusercontent.com/assets/16315601/11921353/8a24657c-a7db-11e5-9abb-b248608dc2b8.PNG)

**Comment by jishi** [comment]
Hi, I'm currently rewriting the underlying library and would like to include support for this. Since I don't own a PLAYBAR, could you perhaps gather how these values are evented? If you are using wireshark, could you please find the requests that include these variables? Since all events are sent directly upon subscription, it means that you would receive all events in a few seconds, right after you start the desktop controller application.

When you have grabbed traffic, you could filter by: `tcp.dstport == 3400` (for windows controller), and then within that filtered result, search by string "DialogLevel" or "NightMode"

**Comment by NovaGL** [comment]
It happens the same way as in the first post, by clicking Speech Enhancement on the controller it does this.

DesiredValue reflects on or off state.

```xml
POST /MediaRenderer/RenderingControl/Control HTTP/1.1
HOST: 192.168.1.13:1400
SOAPACTION: "urn:schemas-upnp-org:service:RenderingControl:1#SetEQ"
CONTENT-TYPE: text/xml; charset="utf-8"
Content-Length: 416

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <u:SetEQ xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
         <InstanceID>0</InstanceID>
         <EQType>DialogLevel</EQType>
         <DesiredValue>1</DesiredValue>
      </u:SetEQ>
   </s:Body>
</s:Envelope>HTTP/1.1 200 OK
CONTENT-LENGTH: 247
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
Server: Linux UPnP/1.0 Sonos/31.8-24090 (ZPS9)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:SetEQResponse xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1"></u:SetEQResponse></s:Body></s:Envelope>
```

Clicking Night Mode does similar

```xml
POST /MediaRenderer/RenderingControl/Control HTTP/1.1
HOST: 192.168.1.13:1400
SOAPACTION: "urn:schemas-upnp-org:service:RenderingControl:1#SetEQ"
CONTENT-TYPE: text/xml; charset="utf-8"
Content-Length: 414

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <u:SetEQ xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
         <InstanceID>0</InstanceID>
         <EQType>NightMode</EQType>
         <DesiredValue>1</DesiredValue>
      </u:SetEQ>
   </s:Body>
</s:Envelope>HTTP/1.1 200 OK
CONTENT-LENGTH: 247
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
Server: Linux UPnP/1.0 Sonos/31.8-24090 (ZPS9)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:SetEQRes
```
To get the current level you poll GetEQ instead of SetEQ

```xml
POST /MediaRenderer/RenderingControl/Control HTTP/1.1
HOST: 192.168.1.13:1400
SOAPACTION: "urn:schemas-upnp-org:service:RenderingControl:1#GetEQ"
CONTENT-TYPE: text/xml; charset="utf-8"
Content-Length: 373

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <u:GetEQ xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
         <InstanceID>0</InstanceID>
         <EQType>NightMode</EQType>
      </u:GetEQ>
   </s:Body>
</s:Envelope>HTTP/1.1 200 OK
CONTENT-LENGTH: 277
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
Server: Linux UPnP/1.0 Sonos/31.8-24090 (ZPS9)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetEQResponse xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1"><CurrentValue>1</CurrentValue></u:GetEQResponse></s:Body></s:Envelope>
```

**Comment by jishi** [comment]
This is great, exactly what I needed. Thanks!

**Comment by maddox** [comment]
Did this ever happen? I'd really love the ability to set the bass level.

**Comment by jishi** [comment]
No, sorry. So much to do, so little time :) I'm gonna do some sub-improvements next, might look at this then.

**Comment by maddox** [comment]
Awesome, thanks!

**Comment by jishi** [comment]
Made SUB improvements. PLAYBAR control and Bass/Treble should be the same, will look into these next.

**Comment by maddox** [comment]
> Made SUB improvements. PLAYBAR control and Bass/Treble should be the same, will look into these next.

I pulled and tried it out, but I keep getting this:

```{"status":"error","error":"This zone doesn't have a SUB connected","stack":"Error: This zone doesn't have a SUB connected\n    at Object.sub (/Users/jmaddox/apps/node-sonos-http-api/lib/actions/sub.js:5:27)\n    at handleAction (/Users/jmaddox/apps/node-sonos-http-api/lib/sonos-http-api.js:110:35)\n    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/Users/jmaddox/apps/node-sonos-http-api/lib/sonos-http-api.js:87:5)\n    at /Users/jmaddox/apps/node-sonos-http-api/server.js:50:13\n    at Server.finish (/Users/jmaddox/apps/node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/Users/jmaddox/apps/node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)\n    at /Users/jmaddox/apps/node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:82:15)"}%                                                                         You have new mail.                           
```

The zone i'm trying it on does in fact have a sub. It's named Family Room. I used `/Family%20Room/sub/off`.

**Comment by jishi** [comment]
@maddox What's your setup? I could only test this with a Connect:AMP and a SUB. One suspicion is that if you have satellites with your PLAYBAR, I might not find the SUB correctly. Is that the case? 

If you can send me a trace log from a startup (where I would get the topology XML), I can fix it.

Start with `NODE_LOG_LEVEL=trace node server.js > trace.log` and let it run for 5-10 seconds, then email the trace.log file to me `jimmy at shimizu.se`. These instructions are for linux and macOS.

**Comment by jishi** [comment]
@maddox I got a dump from a guy who had a stereo pair that suffered from the same issue. I think I have fixed it for that setup at least. Not sure about a PLAYBAR with rear speakers though, but I think it will work for that as well.

**Comment by maddox** [comment]
Here's my dump: https://gist.github.com/maddox/11464503f7067c2c7cff4cde680968e6

I have a stereo pair, but it's not the one that the sub is connected to. My sub is connected to my `Family Room` Playbar.

**Comment by jishi** [comment]
@maddox Aha, PLAYBAR with SUB is widely different than other bondings. I'll try to have a look at it this weekend.

**Comment by jishi** [comment]
@maddox I think I've fixed the SUB identification on PLAYBARs now. Don't own one myself so can't verify 100%. 

I've also finally added the nightmode and speechanhancement options. Hopefully some people will be glad about that :). See README for info.

**Comment by NovaGL** [comment]
Thanks for speech and night mode, took awhile but glad we got there will let you know if I have any issues

**Comment by maddox** [comment]
:/ I'm still getting the `This zone doesn't have a SUB connected` error.

**Comment by jishi** [comment]
@maddox Did you run the `npm install --production` step to get the latest sonos-discovery package? Looking at your trace logging, it matches the test case I used, so I feel like it should work...

**Comment by maddox** [comment]
Yeah, I even wiped `node_modules` and ran it again.

Is there anything else I can do to figure out why it's not seeing it?

**Comment by jishi** [comment]
@maddox Wtf... i actually forgot to push master from my computer at home 😂 

if you modify package.json to use `https://github.com/jishi/node-sonos-discovery/archive/v1.4.0.tar.gz` instead, you would probably see your SUB. NightMode and SpeechEnhancement won't be part of it though. I'll push it when I get home tonight.

**Comment by maddox** [comment]
Ha, i didn't see any changes on master that reflected these new things and was confused. Cool, I'll try it now.

**Comment by maddox** [comment]
It worked!! WOOT! Thanks so much!
